### ISSUE TITLE
Documentation about the package: behaviourtree

### ISSUE THREAD

**Issue by jabrena** [JakubValtar/beacon-follower#1]
Hi,

another day, I found this package and it seem pretty interesting.

I would like to know if you have some documentation about it.
https://github.com/JakubValtar/beacon-follower/tree/master/src/ev3/behaviourtree

Many thanks in advance.

Juan Antonio

**Comment by JakubValtar** [comment]
Hi, this is a custom implementation of behavior trees for this project. If you find this code useful you can take it and do whatever you want with it, but we don't provide any support or have any docs (besides the comments in the code). You can see how it is used in the [src/ev3/Main.java](https://github.com/JakubValtar/beacon-follower/blob/master/src/ev3/Main.java).

You can read more about the concept of behavior trees e.g. at [Chris Simpson's post on Gamasutra](http://www.gamasutra.com/blogs/ChrisSimpson/20140717/221339/Behavior_trees_for_AI_How_they_work.php).

Good luck!
